# fly.toml app configuration file generated for dash2 on 2025-08-20T16:54:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dash2'
primary_region = 'ams'

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/ping"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "echo 'Deployment complete'"
